spring:
  datasource:
    url: jdbc:mysql://localhost:3306/guns
    username: root
    password: root
    # mysql-connector-java >= 6.x com.mysql.cj.jdbc.Driver
    # mysql-connector-java <= 5.x com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
