spring:
  datasource:
    url: jdbc:mysql://localhost:3306/guns?serverTimezone=CTT
    username: root
    password: root
    # mysql-connector-java >= 6.x com.mysql.cj.jdbc.Driver
    # mysql-connector-java <= 5.x com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        #指定nacos server的地址
        server-addr: 172.30.8.74:8848
        # 指定namespace
        #namespace: d1b4f9a9-6316-4bcb-91ac-cdfd3d25c987
        # NJ 假设用户中心部署在南京机房
        # 指定集群名称
        cluster-name: BJ
        metadata:
          instance: c
          haha: hehe
          version: v1
    stream:
      rocketmq:
        binder:
          name-server: 172.30.8.74:9876
      bindings:
        input:
          destination: stream-test-topic
          # 如果用的是RocketMQ,一定要设置
          # 如果用的是其他MQ,可留空
          group: binder-group
        my-input:
          destination: stream-my-topic
          # 如果用的是RocketMQ,一定要设置
          # 如果用的是其他MQ,可留空
          group: my-group
  application:
    # 服务名称尽量用-,不要用_,不要用特殊字符
    name: user-center
  zipkin:
    base-url: http://172.30.8.74:9411/
  sleuth:
    sampler:
      # 抽样率,默认是0.1 (10%)
      probability: 1.0
server:
  port: 8080
rocketmq:
  name-server: 172.30.8.74:9876

jwt:
  secret: 374052753
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600

logging:
  level:
    org.springframework.cloud.sleuth: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always