spring:
  datasource:
    url: jdbc:mysql://localhost:3306/guns
    username: root
    password: root
    # mysql-connector-java >= 6.x com.mysql.cj.jdbc.Driver
    # mysql-connector-java <= 5.x com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        #指定nacos server的地址
        server-addr: 172.30.8.74:8848
  application:
    # 服务名称尽量用-,不要用_,不要用特殊字符
    name: user-center
server:
  port: 8081